parameters:
    ruian.twitterbootstrap.topbar.service.class: Ruian\TwitterBootstrapBundle\Services\TopBarService
    ruian.twitterbootstrap.topbar.helper.class: Ruian\TwitterBootstrapBundle\Helper\TopBarHelper
    ruian.twitterbootstrap.breadcrumb.helper.class: Ruian\TwitterBootstrapBundle\Helper\BreadcrumbHelper
    ruian.twitterbootstrap.alert.helper.class: Ruian\TwitterBootstrapBundle\Helper\AlertHelper

services:
    ruian.twitterbootstrap.topbar:
        class: %ruian.twitterbootstrap.topbar.service.class%
        arguments: [%ruian.twitterbootstrap.topbars%]
    
    ruian.twitterbootstrap.topbar.helper:
        class: %ruian.twitterbootstrap.topbar.helper.class%
        arguments: [@templating, %ruian.twitterbootstrap.engine%, @request, @ruian.twitterbootstrap.topbar]
        scope: request
        tags:
            - { name: templating.helper, alias: ruian.twitterbootstrap.topbar }
    
    ruian.twitterbootstrap.breadcrumb.helper:
        class: %ruian.twitterbootstrap.breadcrumb.helper.class%
        arguments: [@templating, %ruian.twitterbootstrap.engine%, @request]
        scope: request
        tags:
            - { name: templating.helper, alias: ruian.twitterbootstrap.breadcrumb }
    
    ruian.twitterbootstrap.alert.helper:
        class: %ruian.twitterbootstrap.alert.helper.class%
        arguments: [@templating, %ruian.twitterbootstrap.engine%]
        tags:
            - { name: templating.helper, alias: ruian.twitterbootstrap.alert }
